### PR TITLE
Take MDFP into account when recording tracking

### LINKED ISSUE #2351: MDFP domains are marked as tracking in the snitch map
I was investigating #2334, and realized one of my assumptions is wrong. When a third-party domain sets high-entropy cookies, Privacy Badger doesn't check to see whether the domain is on the MDFP list before updating the snitch map. As a result, even though Wikimedia domains are on the list, the seed dataset still has a full `snitch_map` entry for wikimedia.org. See https://github.com/EFForg/privacybadger/blob/master/src/data/seed.json#L10633.

This is because `heuristicBlockingAccounting` doesn't contain any MDFP checks. I think this is a bug because every other place `_recordPrevalence` is called does -- Privacy Badger won't record MDFP domains as trackers when they do fingerprinting or set localstorage cookies.

The fix should be pretty easy, but it will also require a migration (as talked about [here](https://github.com/EFForg/privacybadger/issues/2334#issuecomment-476269021).)

### PR DESCRIPTION
**Pull request by ghostwords**
Fixes #2351.

- [x] Have the "is this a third-party resource?" check take MDFP into account when recording (cookie) tracking. In other words, update the third-party checking before recording cookie tracking (`heuristicblocking.js`) to match the third-party checking before cancelling/modifying requests/responses (`webrequest.js`).
- [x] Add migration to clean up `action_map`/`snitch_map` for existing Badger users, and for Badger users importing previously exported data

Could potentially use [`BadgerStorage.merge()`](https://github.com/EFForg/privacybadger/blob/2b292cfbcee3ffa5f14e0e2dd7541da08264cbb1/src/js/storage.js#L542) to help clean up data.

### CODE REVIEW

File: src/js/background.js [hunk 1]
```diff
@@ -533,6 +533,7 @@ Badger.prototype = {
       Migrations.migrateDntRecheckTimes,
       // Need to run this migration again for everyone to #1181
       Migrations.migrateDntRecheckTimes2,
+      Migrations.migrateMDFPAwareStorageObjects,
```
Comment (ghostwords) [inline src/js/background.js]: Ah, the tests are failing because Badger fails to initialize properly since there is no such migration as `migrateMDFPAwareStorageObjects`:

Screenshot from 2019-06-17 14:04:46

Comment (ghostwords) [reply src/js/background.js]: Our migrations system doesn't support anything except adding a new migration to the back of this array. If you add a migration to the middle of the array, that migration will not run for existing Badgers (as it will be below their migration level); the migration at the back of the array will be re-run instead.

File: src/js/migrations.js [hunk 2]
```diff
@@ -261,6 +262,40 @@ exports.Migrations= {
     }
   },
 
+  forgetFirstPartySnitches: function (badger) {
+    // this needs to happen before unblockIncorrectlyBlockedDomains
```
Comment (ghostwords) [inline src/js/migrations.js]: If we need to rerun `unblockIncorrectlyBlockedDomains()`, we should just call that function manually from our new migration.

File: src/js/migrations.js [hunk 3]
```diff
@@ -261,6 +262,40 @@ exports.Migrations= {
...
+
+    let snitchMap = badger.storage.getBadgerStorageObject("snitch_map"),
+      items = snitchMap.getItemClones();
+
+    for (let domain in items) {
+      let snitches = snitchMap.getItem(domain);
+      let newSnitches = [];
+
+      snitches.forEach(function (snitch) {
+        if (!mdfp.isMultiDomainFirstParty(snitch, domain)) {
```
Comment (ghostwords) [inline src/js/migrations.js]: We should use `utils.isThirdPartyDomain()` here instead, to match what we do as part of standard operation.

File: src/js/migrations.js (hunk 2 above)
Comment (ghostwords) [reply src/js/migrations.js]: I am not sure `unblockIncorrectlyBlockedDomains()` is the right approach here though. It only looks at blocked domains, so it wouldn't clean up domains that shouldn't be in `action_map` at all (two `snitch_map` entries --> no `snitch_map` entries).

I think it's worth looking into creating a new `snitch_map` object from the old `snitch_map` object and then calling `mergeUserData()` on the new `snitch_map` + old `action_map`. I could be missing something here though as I haven't tried it myself, just a hunch.

File: src/js/background.js (hunk 1 above)
Comment (ablanathtanalba) [reply src/js/background.js]: Thanks for pointing that out! I'll move it to the end of the array.

File: src/js/migrations.js (hunk 3 above)
Comment (ablanathtanalba) [reply src/js/migrations.js]: Makes sense! Thanks

File: src/js/migrations.js (hunk 2 above)
Comment (ablanathtanalba) [reply src/js/migrations.js]: Correct me if I'm wrong, but you're suggesting that the logic remain mostly the same, but to append at the end `mergeUserData(snitchMap, actionMap)` ? Perhaps I'm misunderstanding how `mergeUserData` works.

Comment (ghostwords) [reply src/js/migrations.js]: The logic will be similar but not the same. Right now you're modifying snitch map directly and then relying on `unblockIncorrectlyBlockedDomains()` to fix action map.

I suggest that `unblockIncorrectlyBlockedDomains()` is not a good fit for this task (as it was made to solve a different problem). I further suggest to try copying snitch map to a temporary snitch map (filtering out not-actually-third-party entries), and then using `mergeUserData()` to rebuild action map and snitch map. The underlying `merge()` function should take care of properly rebuilding action and snitch maps. We may need to blank out existing snitch and action maps right before importing, to clear out the entries for trackers that shouldn't be there any more at all.

Something like the following? Take a look at how and where we use `mergeUserData()` and `merge()` now and what they do.

```javascript
let data = {
  snitch_map: correctedSnitchMap,
  action_map: actionMap,
};
snitchMap.updateObject({});
actionMap.updateObject({});
badger.mergeUserData(data);
```

**Comment by ablanathtanalba** [comment]
Seems like an infinite loop is created by pinning `mergeUserData` at the tail end of the proposed migration because it is also called in `runMigrations`

File: src/js/background.js [hunk 4]
```diff
@@ -824,8 +825,9 @@ Badger.prototype = {
    * Merge data exported from a different badger into this badger's storage.
    *
    * @param {Object} data the user data to merge in
+   * @param {Undefined} runInMigration undefined in all cases except when this function is run in a migration, then prevents infinite loop
```
Comment (ghostwords) [inline src/js/background.js]: Should be something like the following (JSDoc convention for an optional boolean that defaults to false, also naming convention: let's use Java naming for objects/object properties/methods, and C naming for primitives):
```
@param {Boolean} [from_migration=false] set when running from a migration to avoid infinite loop
```

File: src/js/heuristicblocking.js [hunk 5]
```diff
@@ -124,25 +124,25 @@ HeuristicBlocker.prototype = {
       self = this;
 
     // ignore first-party requests
-    if (!tab_origin || origin == tab_origin) {
+    if (!utils.isThirdPartyDomain(request_origin, tab_origin)) {
```
Comment (ghostwords) [inline src/js/heuristicblocking.js]: Should restore the `!tab_origin` portion of the check since `tab_origin` may in fact be falsy and we don't want to keep going in that case.

File: src/js/migrations.js [hunk 6]
```diff
@@ -261,6 +261,44 @@ exports.Migrations= {
...
+    let snitchMap = badger.storage.getBadgerStorageObject("snitch_map"),
+      actionMap = badger.storage.getBadgerStorageObject("action_map"),
+      snitchClones = snitchMap.getItemClones(),
+      actionClones = actionMap.getItemClones();
+
+    for (let domain in snitchClones) {
+      // creates new array of domains checking against the isThirdParty utility
+      let newSnitches = snitchClones[domain].filter(item => utils.isThirdPartyDomain(item, domain));
+
+      // if that list has changed, reassign or delete the entry as necessary
```
Comment (ghostwords) [inline src/js/migrations.js]: This works, but we can simplify by creating a new, corrected `snitchMapClones` instead of modifying (and then restoring) snitch map directly. Something like the following?

```diff
diff --git a/src/js/migrations.js b/src/js/migrations.js
index 854d89a..035a07e 100644
--- a/src/js/migrations.js
+++ b/src/js/migrations.js
@@ -263,35 +263,29 @@ exports.Migrations= {
 
   forgetFirstPartySnitches: function (badger) {
     console.log("Removing first parties from snitch map...");
+
     let snitchMap = badger.storage.getBadgerStorageObject("snitch_map"),
       actionMap = badger.storage.getBadgerStorageObject("action_map"),
       snitchClones = snitchMap.getItemClones(),
-      actionClones = actionMap.getItemClones();
+      actionClones = actionMap.getItemClones(),
+      correctedSites = {};
 
     for (let domain in snitchClones) {
       // creates new array of domains checking against the isThirdParty utility
-      let newSnitches = snitchClones[domain].filter(item => utils.isThirdPartyDomain(item, domain));
+      let newSnitches = snitchClones[domain].filter(
+        item => utils.isThirdPartyDomain(item, domain));
 
-      // if that list has changed, reassign or delete the entry as necessary
-      if (newSnitches.length === 0) {
-        console.log('removing : ', domain);
-        snitchMap.deleteItem(domain);
-        continue;
-      }
-      if (newSnitches.length !== snitchClones[domain].length) {
-        console.log('reassigning : ', domain);
-        snitchMap.setItem(domain, newSnitches);
+      if (newSnitches.length) {
+        correctedSites[domain] = newSnitches;
       }
     }
 
-    // reset the snitch map clones object to the updated snitch map
-    snitchClones = snitchMap.getItemClones();
-
+    // clear existing maps and then use mergeUserData to rebuild them
     actionMap.updateObject({});
     snitchMap.updateObject({});
 
     const data = {
-      snitch_map: snitchClones,
+      snitch_map: correctedSites,
       action_map: actionClones
     };
```

File: src/js/utils.js [hunk 7]
```diff
@@ -22,6 +22,8 @@
 
 require.scopes.utils = (function() {
 
+var mdfp = require("multiDomainFP");
```
Comment (ghostwords) [inline src/js/utils.js]: Should stick to 'let' going forward.

File: src/tests/tests/background.js [hunk 8]
```diff
@@ -357,4 +358,53 @@ QUnit.test("subdomains on the yellowlist are preserved", (assert) => {
...
 
+QUnit.test("migrates misattributed MDFP domains from snitch map", (assert) => {
+  setupBadgerStorage(badger);
+
+  // store one action map for all tests (should always be preserved)
+  const actionMap = badger.storage.getBadgerStorageObject('action_map'),
+    snitchMap = badger.storage.getBadgerStorageObject('snitch_map');
+
+  // reset snitchMap's storage to blank object
+  snitchMap.updateObject({});
```
Comment (ghostwords) [inline src/tests/tests/background.js]: No need since we overwrite snitch map before every assertion.

File: src/tests/tests/background.js [hunk 9]
```diff
@@ -357,4 +358,53 @@ QUnit.test("subdomains on the yellowlist are preserved", (assert) => {
...
+  snitchMap.updateObject(snitchNoMDFP);
+  migrations.forgetFirstPartySnitches(badger);
+  assert.ok(badger.storage.getBadgerStorageObject('snitch_map').getItem('amazon.com'),
+    'forget first party migration does not affect a snitchmap with no misattributed MDFP items'
+  );
+
+  // tests that a snitchMap entry with some MDFP domains has those items removed but remains in the snitch Map
+  snitchMap.updateObject(snitchSomeMDFP);
+  migrations.forgetFirstPartySnitches(badger);
+  assert.equal(snitchMap.getItem('amazon.com')[0] === 'amazing.com' && snitchMap.getItem('amazon.com').length === 1, true,
```
Comment (ghostwords) [inline src/tests/tests/background.js]: Should be `assert.deepEqual()`.

File: src/tests/tests/background.js [hunk 10]
```diff
@@ -357,4 +358,53 @@ QUnit.test("subdomains on the yellowlist are preserved", (assert) => {
...
+
+  // tests that a snitchMap entry with all MDFP domains will have all domains removed then removed entirely from snitchMap
+  snitchMap.updateObject(snitchAllMDFP);
+  migrations.forgetFirstPartySnitches(badger);
+  assert.notOk(snitchMap.getItem('amazon.com'),
+    'forget first party migration properly removes a snitch map entry with all MDFP domains attributed to it');
+
+
+  // action map stays the same throughout all tests
+  assert.equal(actionMap, badger.storage.getBadgerStorageObject('action_map'), 'action map stays the same after running migration');
```
Comment (ghostwords) [inline src/tests/tests/background.js]: Should be `assert.deepEqual()`, and should be comparing `getItemClones()`. But I don't think this check makes sense: action map should indeed change for every test. We should set up and verify the contents of action map for each of the three scenarios.

File: src/tests/tests/background.js [hunk 11]
```diff
@@ -357,4 +358,53 @@ QUnit.test("subdomains on the yellowlist are preserved", (assert) => {
...
+  // snitch map with some MDFP entries
+  let snitchSomeMDFP = {
+    ['amazon.com']: ['amazon.ca', 'amazon.co.jp', 'amazing.com']
+  };
+
+  // snitch map with all MDFP entries
+  let snitchAllMDFP = {
+    ['amazon.com']: ['amazon.ca', 'amazon.co.jp', 'amazon.es']
+  };
+
```
Comment (ghostwords) [inline src/tests/tests/background.js]: We should either overwrite (and afterwards restore) actual MDFP data with our test data, or we should confirm that the assumptions we make about the contents of MDFP hold true. The latter seems a bit easier. Something like the following?
```javascript
  // confirm our MDFP assumptions
  ['amazon.ca', 'amazon.co.jp', 'amazon.es'].forEach(function (domain) {
    assert.ok(
      mdfp.isMultiDomainFirstParty('amazon.com', domain),
      domain + " is indeed MDFP to amazon.com"
    );
  });
```

File: src/tests/tests/background.js [hunk 12]
```diff
@@ -357,4 +358,53 @@ QUnit.test("subdomains on the yellowlist are preserved", (assert) => {
   );
 });
 
+QUnit.test("migrates misattributed MDFP domains from snitch map", (assert) => {
+  setupBadgerStorage(badger);
```
Comment (ghostwords) [inline src/tests/tests/background.js]: We don't make use of any of the test fixture data in `setupBadgerStorage()` in this test ...

File: src/tests/tests/background.js [hunk 13]
```diff
@@ -357,4 +358,53 @@ QUnit.test("subdomains on the yellowlist are preserved", (assert) => {
...
+
+  // store one action map for all tests (should always be preserved)
```
Comment (ghostwords) [inline src/tests/tests/background.js]: Shouldn't be true, see comment below.

File: src/tests/tests/background.js (hunk 10 above)
Comment (ghostwords) [reply src/tests/tests/background.js]: Something like:
```javascript
  let actionNoMDFP = {
    'amazon.com': {
      heuristicAction: "cookieblock",
      userAction: "",
      dnt: false,
      nextUpdateTime: 0,
    }
...
  snitchMap.updateObject(snitchNoMDFP);
  actionMap.updateObject(actionNoMDFP);
  migrations.forgetFirstPartySnitches(badger);
...
  assert.deepEqual(
    actionMap.getItem('amazon.com'),
    actionNoMDFP['amazon.com'],
    "action map preserved for domain with no MDFP snitch entries"
  );
...
  assert.equal(
    badger.storage.getAction('amazon.com'),
    constants.ALLOW,
    "Action downgraded for partial MDFP domain"
  );
...
```

File: src/tests/tests/background.js [hunk 14]
```diff
@@ -357,4 +358,53 @@ QUnit.test("subdomains on the yellowlist are preserved", (assert) => {
   );
 });
 
+QUnit.test("migrates misattributed MDFP domains from snitch map", (assert) => {
```
Comment (ghostwords) [inline src/tests/tests/background.js]: We might want to break this up into three separate tests, especially once you add the extra assertions for action map contents (see below).

File: src/js/migrations.js (hunk 6 above)
Comment (ablanathtanalba) [reply src/js/migrations.js]: Nice -- I like this simplification! Much more readable and reduces some clutter

**Comment by ablanathtanalba** [comment]
Thanks @ghostwords ! Appreciate the feedback. I've gone through and addressed each point in the most recent commits.

File: src/tests/tests/background.js [hunk 15]
```diff
@@ -357,4 +359,107 @@ QUnit.test("subdomains on the yellowlist are preserved", (assert) => {
...
+    'forget first party migration does not affect a snitchmap with no misattributed MDFP items'
+  );
+});
+
+QUnit.test("forgetFirstPartySnitches migration properly handles snitch entries with some MDFP entries", (assert) => {
+  const actionMap = badger.storage.getBadgerStorageObject('action_map'),
+    snitchMap = badger.storage.getBadgerStorageObject('snitch_map');
+
+  let snitchSomeMDFP = {
+    ['amazon.com']: ['amazon.ca', 'amazon.co.jp', 'amazing.com']
```
Comment (ghostwords) [inline src/tests/tests/background.js]: The key should be a string.

File: src/tests/tests/background.js [hunk 16]
```diff
@@ -357,4 +359,107 @@ QUnit.test("subdomains on the yellowlist are preserved", (assert) => {
...
+    true,
+    'forget first party migration properly removes MDFP domains and leaves regular domains');
+});
+
+QUnit.test("forgetFirstPartySnitches migration properly handles snitch entries with all MDFP entries", (assert) => {
+  const actionMap = badger.storage.getBadgerStorageObject('action_map'),
+    snitchMap = badger.storage.getBadgerStorageObject('snitch_map');
+
+  let snitchAllMDFP = {
+    ['amazon.com']: ['amazon.ca', 'amazon.co.jp', 'amazon.es']
```
Comment (ghostwords) [inline src/tests/tests/background.js]: The key should be a string.

File: src/tests/tests/background.js [hunk 17]
```diff
@@ -357,4 +359,107 @@ QUnit.test("subdomains on the yellowlist are preserved", (assert) => {
   );
 });
 
+QUnit.test("forgetFirstPartySnitches migration properly handles snitch entries with no MDFP entries", (assert) => {
+  const actionMap = badger.storage.getBadgerStorageObject('action_map'),
+    snitchMap = badger.storage.getBadgerStorageObject('snitch_map');
+
+  let snitchNoMDFP = {
+    ['amazon.com']: ['amazonads.com', 'amazing.com', 'amazonrainforest.com']
```
Comment (ghostwords) [inline src/tests/tests/background.js]: The key should be a string.

File: src/tests/tests/background.js [hunk 18]
```diff
@@ -357,4 +359,107 @@ QUnit.test("subdomains on the yellowlist are preserved", (assert) => {
...
+  actionMap.updateObject(actionSomeMDFP);
+  migrations.forgetFirstPartySnitches(badger);
+
+  assert.equal(
+    badger.storage.getAction('amazon.com'),
+    constants.ALLOW,
+    "Action downgraded for partial MDFP domain"
+  );
+
+  assert.deepEqual(snitchMap.getItem('amazon.com')[0] === 'amazing.com' && snitchMap.getItem('amazon.com').length === 1,
```
Comment (ghostwords) [inline src/tests/tests/background.js]: What I meant earlier is that we should take advantage of `assert.deepEqual()` and simplify the checks here. Instead of checking the first item of the array and the length of the array, we could just compare all of `snitchMap.getItem('amazon.com')` to what we expect it to be.

File: src/tests/tests/background.js [hunk 19]
```diff
@@ -357,4 +359,107 @@ QUnit.test("subdomains on the yellowlist are preserved", (assert) => {
...
+  actionMap.updateObject(actionNoMDFP);
+  migrations.forgetFirstPartySnitches(badger);
+
+  assert.deepEqual(
+    actionMap.getItem('amazon.com'),
+    actionNoMDFP['amazon.com'],
+    "action map preserved for domain with no MDFP snitch entries"
+  );
+
+  assert.ok(badger.storage.getBadgerStorageObject('snitch_map').getItem('amazon.com'),
```
Comment (ghostwords) [inline src/tests/tests/background.js]: Should compare against the actual expected snitch map instead.

File: src/tests/tests/background.js [hunk 20]
```diff
@@ -357,4 +359,107 @@ QUnit.test("subdomains on the yellowlist are preserved", (assert) => {
...
+
+  // confirm all entries are MDFP
+  snitchAllMDFP["amazon.com"].forEach((domain) => {
+    assert.ok(
+      mdfp.isMultiDomainFirstParty('amazon.com', domain),
+      domain + " is indeed MDFP to amazon.com"
+    );
+  });
+
+  assert.notOk(snitchMap.getItem('amazon.com'),
```
Comment (ghostwords) [inline src/tests/tests/background.js]: This assertion doesn't seem to be in the right place.
