### PR TITLE
Google link unwrapping improvements

### LINKED ISSUE #2543: google.* and link blanker extension
Hi, since i've installed this extension the behaviour of tabs opening on google.* went broken.
i use link blanker to automatically open links in a new tab (https://chrome.google.com/webstore/detail/link-blanker/lkafdfakakndhpcpccjnclopfncckhfn).
disabling this extension makes the behaviour become normal again, but upon activating it reappears.
in short what happens is that it does not let me anymore open links in new tabs as instructed by the link blanker but will open them in the current tab instead.
it is weird because on other sites everything seems to work normally.

### LINKED ISSUE #2866: Google search link unwrapping doesn't work on image search results
When on a google search result page, right-clicking the true URL to copy it now gives me the google tracking url again instead. Privacy Badger used to fix this and is one of its best features. It would be great if it could be fixed again. I'm using PB on Firefox.

### LINKED ISSUE #2900: Google search link unwrapping doesn't work with endless scroll
When I do a google search, privacy badger prevents google from changing the links at the last second (upon clicking or right-clicking) to their tracking version. This works fine until you scroll down past a certain point.

Nowadays google search results use an "endless scrolling" type of feature where more results are loaded when you scroll down past a certain point. All the links past the first group of results are using the tracking links, so privacy badger isn't fixing them.

### PR DESCRIPTION
**Pull request by ghostwords**
Fixes #2866, fixes #2900, fixes #2543, fixes #2719.

This fixes cleaning links in image search, Google Docs, Gmail and Google Maps, as well as links added after scrolling the search results page.

Often the link destination is replaced with a redirect URL in response to interaction with the link. Sometimes we catch this mutation in the content script and fix the link in time. Sometimes the page uses a more complicated approach to covertly open a redirect URL at the last moment, which we don't catch in the content script. We work around these cases by redirecting the redirect request to the expected destination in the network layer.

We still want to use a content script to ensure users can copy/paste clean link URLs, and to avoid an unnecessary redirect.

We no longer try to prevent links from triggering `/gen_204` requests in the content scripts, but rather block all `/gen_204` ping/beacon requests in the network layer.

#### Testing notes

✔️: wrapped links that we fix in the content script
😐: more advanced (`window.open()`-based) wrapping that we handle via the network redirect fallback

| browser →<br>site ↓ | Chrome | Firefox | Firefox for Android |
| :---: | :---: | :---: | :---: |
| **text search** | no href wrapping | ✔️<br>links wrapped on interaction | ✔️ |
| **image search** | 😐 ✔️<br>links wrapped on interaction,<br>content script unwraps but too late for navigation | 😐 ✔️<br>links wrapped on interaction,<br>content script unwraps but too late for navigation | ✔️<br>"lite" version |
| **Docs**<br>[example](https://docs.google.com/document/d/1xOe5e8CDU9HM6sazGg6aqvK0iPnptilmwBS9qiZSfkY/) | doc body links: 😐<br>comment links: ✔️ | doc body links: 😐<br>comment links: ✔️ | ✔️<br>`/mobilebasic` version with double-wrapped (??) links |
| **Sheets**<br>[example](https://docs.google.com/spreadsheets/d/1PMx-FZJwOEd9PxAsdraqLsDgSjvhWIT-ZEg5Pe8b21o/) | 😐 | 😐 | ✔️<br>`/htmlview` version |
| **Gmail** | 😐 | 😐 | no href wrapping or window opening trickery |
| **Maps** | 😐 | 😐 | ✔️ |

Country code TLDs (e.g. `google.co.jp`): Same as above, but our content script should still successfully handle country TLD-wrapped links (`www.google.co.jp/url?`), and our network redirect fallback should handle the country TLD redirect.

### CODE REVIEW

File: src/js/webrequest.js [hunk 1]
```diff
@@ -325,6 +325,65 @@ function blockMozCspReports(details) {
...
+ *
+ * @param {Object} details webRequest request details object
+ *
+ * @returns {Object|undefined} Can redirect requests
+ */
+function bypassGoogleRedirects(details) {
+  if (!badger.INITIALIZED) { return; }
+  let request_host = extractHostFromURL(details.url);
+  if (!badger.isPrivacyBadgerEnabled(request_host)) { return; }
+  let urlObj, redirect_url;
```
Comment (zoracon) [inline src/js/webrequest.js:343]: Suggesting to collapse these statements since they both lead to return on `false`.

```suggestion
  let request_host = extractHostFromURL(details.url);
  let urlObj, redirect_url;
  if (!badger.INITIALIZED || !badger.isPrivacyBadgerEnabled(request_host)) {
    return;
  }
```

File: src/js/webrequest.js [hunk 2]
```diff
@@ -325,6 +325,65 @@ function blockMozCspReports(details) {
...
+  }
+  if (redirect_url) {
+    if (redirect_url.startsWith("https://") || redirect_url.startsWith("http://")) {
+      if (utils.isThirdPartyDomain(extractHostFromURL(redirect_url), request_host)) {
+        return {
+          redirectUrl: redirect_url
+        };
+      }
+    }
+  }
```
Comment (zoracon) [inline src/js/webrequest.js:358]: Suggesting some logic eval set to variables so to avoid the nested ifs.
```suggestion
  let isHttpUrl = redirect_url.startsWith('https://') || redirect_url.startsWith('http://');
  let isThirdPartyDomain = utils.isThirdPartyDomain(extractHostFromURL(redirect_url), request_host);

  if (redirect_url && isHttpUrl && isThirdPartyDomain ) {
    return {
      redirectUrl: redirect_url
    };
  }
```

File: src/js/webrequest.js (hunk 1 above)
Comment (zoracon) [reply src/js/webrequest.js:343]: **Note**: I did not locally evaluate this code. So don't merging here may cause an error. The same goes for the rest of ny comments with code.

File: src/js/webrequest.js [hunk 3]
```diff
@@ -325,6 +325,65 @@ function blockMozCspReports(details) {
...
+ *
+ * @returns {Object|undefined} Can cancel requests
+ */
+function blockGoogleGen204s(details) {
+  if (!badger.INITIALIZED) { return; }
+
+  let frameData = badger.tabData.getFrameData(details.tabId);
+  if (!frameData) {
+    return;
+  }
```
Comment (zoracon) [inline src/js/webrequest.js:374]: More return collapsing here for readability.
```suggestion
let frameData = badger.tabData.getFrameData(details.tabId);
if (!badger.INITIALIZED || !frameData) { return; }
```

File: src/js/webrequest.js [hunk 4]
```diff
@@ -1823,6 +1882,36 @@ function startListeners() {
     }, ['blocking', 'requestBody']);
   }
 
+  let googleHosts;
+  try {
+    googleHosts = chrome.runtime.getManifest().content_scripts
+      .find(i => i.js.includes("js/firstparties/google.js")
+        || i.js.includes(chrome.runtime.getURL("js/firstparties/google.js")))
+      .matches.filter(i => i.startsWith("https://www.") && i.endsWith("/*"))
+      .map(i => i.slice(8).slice(0, -2));
```
Comment (zoracon) [inline src/js/webrequest.js:1891]: Nice use of mapping through those hosts here.

**Review by zoracon — COMMENTED** [review]
Had a few comments to collapse some conditions. Otherwise the rest is clear to me.

File: src/js/webrequest.js (hunk 1 above)
Comment (ghostwords) [reply src/js/webrequest.js:343]: It's important to check `badger.INITIALIZED` before anything else happens as event listeners could be called before Privacy Badger's various internals are ready to respond. Also here we don't need to do the work of extracting the host from URL if Badger is not yet initialized.

File: src/js/webrequest.js (hunk 3 above)
Comment (ghostwords) [reply src/js/webrequest.js:374]: Same as above. Tab data may not yet be ready to be read; attempting to read it before Badger is initialized will result in errors.

File: src/js/webrequest.js (hunk 2 above)
Comment (ghostwords) [reply src/js/webrequest.js:358]: If we don't have a redirect URL or it's not a valid URL, we don't need to do the work of host extraction and third party checking. I agree though that the nesting is not great and if it gets any messier, it should be refactored.

File: src/js/webrequest.js (hunk 1 above)
Comment (zoracon) [reply src/js/webrequest.js:343]: Is there a global way to check `badger.INITIALIZED`? Just noticing you have to check in function a few times.

Comment (ghostwords) [reply src/js/webrequest.js:343]: There are a bunch of event listeners, and most of them check `badger.INITIALIZED` (I think there are a few that don't have to).

We need to register event listeners ASAP (in the first turn of the event loop), but we don't want to generate errors when the listeners get called before our various async-init data structures are ready.

We could create a layer of indirection, perhaps a utility function that creates event listener functions. That could certainly be an improvement in the future; I intentionally postpone adding layers as much as possible.
