### PR TITLE
Fix issues with google link unwrapping

### LINKED ISSUE #2181: breaks google search setting to open new tab immediately on click of search result link
firefox nightly 64.0a1 (2018-10-04) (64-bit)
on ubuntu 16.04

I have been using ff nightly for years and your privacybadger for a long time too and its only started failing the other day ... I have google search setting to 

    Where results open
    Open each selected result in a new browser window

which works fine when your addon is disabled ... now when addon enabled 
browser fails to open google search result link in a new tab, now link is opened in same tab
 ... here is such a link

https://www.google.com/search?q=Where+results+open+Open+each+selected+result+in+a+new+browser+window+++fails+to+open+new+tab+or+window&ie=utf-8&oe=utf-8&client=firefox-b-1-ab

### PR DESCRIPTION
**Pull request by bcyphers**
When cleaning links, don't remove 'about', 'class', or 'aria-*' attributes. Fixes #2181.

### CODE REVIEW

**Comment by bcyphers** [comment]
Is it worth adding the same exceptions to the hangouts/docs comment unwrapping?

File: src/js/firstparties/google-static.js [hunk 1]
```diff
@@ -10,7 +10,8 @@ function unwrapLink(a) {
   // remove all attributes from a link except for target
```
Comment (ghostwords) [inline src/js/firstparties/google-static.js]: Could you fix the comment (and perhaps rebase to avoid the merge)?
