### PR TITLE
Fix replacement widget styles

### LINKED ISSUE #890: Tiny social integration (Twitter) button replaced by Privacy Badger, is now HUGE
Small Twitter button replaced by Privacy Badger turned gigantic.

Without Privacy Badger:
image

With:
image

This happend [Here](https://zachholman.com/posts/documentation/), with Privacy Badger 2016.5.24, running in Chrome Version 52.0.2743.82 (64-bit) on Ubuntu 16.04.

### PR DESCRIPTION
**Pull request by rak-phillip**
Fix #890. Made styles for replacement button inline in order to increase precedence for rendering of styles defined by privacy badger.

### CODE REVIEW

File: src/js/contentscripts/socialwidgets.js [hunk 1]
```diff
@@ -118,6 +118,10 @@ function createReplacementButtonImage(tracker, trackerElem) {
   button.setAttribute("class", "privacyBadgerReplacementButton");
```
Comment (ghostwords) [inline src/js/contentscripts/socialwidgets.js]: We no longer need this class, right?

File: src/skin/socialwidgets/socialwidgets.css [hunk 2]
```diff
@@ -42,14 +42,7 @@
...
-
-.privacyBadgerReplacementButton {
-	border: none !important;
-	cursor: pointer !important;
-	height: auto !important;
-	width: auto !important;
-}
-
+	
 .privacyBadgerOriginalButton {
```
Comment (ghostwords) [inline src/skin/socialwidgets/socialwidgets.css]: Could we inline these as well? Then we can drop the whole `socialwidgets.css` file and remove a bunch of code from `socialwidgets.js` (yay!).

File: src/js/contentscripts/socialwidgets.js (hunk 1 above)
Comment (rak-phillip) [reply src/js/contentscripts/socialwidgets.js]: I don't think so, but I'll double check to make sure. I originally left it in because I didn't want to be too liberal with stripping things out.

File: src/skin/socialwidgets/socialwidgets.css (hunk 2 above)
Comment (rak-phillip) [reply src/skin/socialwidgets/socialwidgets.css]: I don't see why not - I'll check it out and follow up.

Comment (rak-phillip) [reply src/skin/socialwidgets/socialwidgets.css]: I removed `socialwidgets.css` and relevant code from `socialwidgets.js`. This might warrant a quick review, but I don't think that I left any artifacts that added the stylesheet.

**Comment by ghostwords** [comment]
Looks good, thank you!
