### PR TITLE
Fix DNT checking for blocked domains

### LINKED ISSUE #1397: Privacy badger blocked domains before they could say they DNT
I will try to find simple steps to reproduce this issue but when I visited [this website](https://troisiemebaobab.com/), the layout was completely messed up.

I suspected it was due to privacy badger blocking `cdn-images-1.medium.com` and `cdn-static-1.medium.com`.

To test this hypothesis before filing an issue, I disabled privacy badger and everything looked fine.

But to my surprise, when I re-enabled privacy badger, the first party still looked fine and `cdn-images-1.medium.com` and `cdn-static-1.medium.com` were now tagged as `DNT`.

I am suspecting they were blocked before they could be contacted to see if they respect DNT. Is that possible?

### LINKED ISSUE #1398: Blocked domains never get rechecked for Do Not Track compliance
And thus will never be unblocked as it stands. We check for DNT inside `chrome.webRequest.onBeforeSendHeaders` and `chrome.webRequest.onResponseStarted`, both of which happen after `chrome.webRequest.onBeforeRequest`, which is where blocking happens.

### PR DESCRIPTION
**Pull request by cowlicks**
closes #1398 and closes #1397

The fix is 4819c06 I add a call to `checkForDNTPolicy` in places where we cancel requests.

Migration to unblock eff.org and its subdomains is fafbd5d.

Removed extra `nextUpdate` argument from `checkForDNTPolicy` in  ef51841 I update the tests and usage in the code to reflect this API change.

Moved the getter/setter functions from the tests into utils.js, and documented them. I use these in other currently pending pull requests, so I'd like to have them included here bb23c55

### CODE REVIEW

**Comment by ghostwords** [comment]
I edited the description: you have to prefix each issue number with "fixes" in order for auto-resolving to work.

**Comment by ghostwords** [comment]
Good catch with https://github.com/EFForg/privacybadger/pull/1642/commits/c3fbc9726f578fd057ccbeb48843a34a9785d7ed! Could you break that out into a separate PR please? If it's not connected to fixing the DNT bug, I'd like to consider what this means for surrogates on its own, outside of us trying to get this fix out.

File: src/js/webrequest.js [hunk 1]
```diff
@@ -103,6 +103,7 @@ function onBeforeRequest(details){
       };
       chrome.tabs.sendMessage(tab_id, msg);
 
+      badger.checkForDNTPolicy(requestDomain, badger.storage.getNextUpdateForDomain(requestDomain));
```
Comment (ghostwords) [inline src/js/webrequest.js]: Could we make both of these calls in `webrequest.js` async, to avoid delaying request resolution as much as we can?   Done elsewhere in `heuristicblocking.js`:
https://github.com/EFForg/privacybadger/blob/1e3d0e748b1027b5854d06afb00237702d65bef8/src/js/heuristicblocking.js#L124-L126

File: src/js/webrequest.js [hunk 2]
```diff
@@ -158,20 +159,14 @@ function onBeforeSendHeaders(details) {
...
-      }
-
       // Notify the content script...
       var msg = {
         replaceSocialWidget: true,
         trackerDomain: requestDomain
       };
       chrome.tabs.sendMessage(tab_id, msg);
 
+      badger.checkForDNTPolicy(requestDomain);
```
Comment (ghostwords) [inline src/js/webrequest.js]: Could we make both `checkForDNTPolicy` calls in `webrequest.js` async, to avoid delaying request resolution as much as we can?   Done elsewhere in `heuristicblocking.js`:
https://github.com/EFForg/privacybadger/blob/1e3d0e748b1027b5854d06afb00237702d65bef8/src/js/heuristicblocking.js#L124-L126

File: src/tests/tests/background.js [hunk 3]
```diff
@@ -144,11 +141,11 @@
     let done = assert.async(NUM_TESTS);
 
     assert.expect(NUM_TESTS);
+    badger.storage.getNextUpdateForDomain = () => 0;
```
Comment (ghostwords) [inline src/tests/tests/background.js]: Do we need to restore this override?

File: src/js/migrations.js [hunk 4]
```diff
@@ -181,6 +181,17 @@ exports.Migrations= {
     }
   },
 
+  unblockEff: function(badger) {
```
Comment (ghostwords) [inline src/js/migrations.js]: Do we actually need the migration?

**Comment by ghostwords** [comment]
Could we rebase on master and remove the hand-rolled mocking, as discussed in https://github.com/EFForg/privacybadger/pull/1618#discussion_r136406737?

File: src/js/migrations.js (hunk 4 above)
Comment (cowlicks) [reply src/js/migrations.js]: It is for good measure, not all subdomains are DNT compliant. So if `eff.org` is blocked, then `act.eff.org` will still load, but  `anon-stats.eff.org` will be blocked bc it isn't DNT compliant.

File: src/tests/tests/background.js (hunk 3 above)
Comment (cowlicks) [reply src/tests/tests/background.js]: It's done above automatically in the `beforeEach`

**Comment by cowlicks** [comment]
@ghostwords would you mind if I leave the tests helpers in?

I'd like to discuss deprecating sinon usage, while we're having the discussion, I think it would be good to limit the spread of sinon. I also think it would be helpful to that discussion if we try out other alternatives (like this). If sinon turns out to be better, I'm happy to go back and apply in to these tests.

**Comment by ghostwords** [comment]
Also, it would be really good to know how to reproduce this as regular Privacy Badger users. If we don't know how it happens in practice, we may miss something in our fix.

**Comment by cowlicks** [comment]
@ghostwords https://github.com/EFForg/privacybadger/pull/1642/commits/c3fbc9726f578fd057ccbeb48843a34a9785d7ed is in #1648. It was included here because it is a small change that should have minimal effect.

I also removed the change to the `Remove netxUpdate arg from checkForDntPolicy` commit. Since this is what required the changes to the tests. I think it is a good api change, so I'll leave that part open as a WIP PR, and maybe someone can adapt it to use sinon.

**Comment by ghostwords** [comment]
Right, but the change doesn't have anything to do with this PR (that we are trying to get done ASAP). Thanks for moving it out to #1648. It would be good to consider what bugs that faulty code might have been causing, but we don't need to consider them here.

**Comment by ghostwords** [comment]
`checkForDNTPolicy` argument update: It does seem like a good API change. I didn't ask for it to get removed, but sure, that works too.

File: src/js/webrequest.js (hunk 1 above)
Comment (ghostwords) [inline src/js/webrequest.js]: Should we make both checkForDNTPolicy calls in webrequest.js async, to avoid delaying request resolution as much as we can? Previously requested in https://github.com/EFForg/privacybadger/pull/1642#discussion_r137572271.

**Comment by ghostwords** [comment]
@cowlicks Could you look into how to reproduce the bug we're fixing here as a regular user?

**Comment by ghostwords** [comment]
Test pages:
- https://stopsesta.org/
- https://savecrypto.org/
- https://necessaryandproportionate.org/sign
- https://efforg.github.io/stop-sesta/ (same as `stopsesta.org` but on GitHub)

File: src/js/background.js [hunk 5]
```diff
@@ -480,6 +480,7 @@ Badger.prototype = {
       Migrations.migrateDntRecheckTimes2,
       Migrations.forgetMistakenlyBlockedDomains,
       Migrations.unblockIncorrectlyBlockedDomains,
+      Migrations.unblockEff,
```
[the remark this answers is not in the document]
Comment (ghostwords) [reply src/js/background.js]: Also, this doesn't just unblock, it removes any `eff.org` domains from Privacy Badger's memory. More like `forgetEFF`.

[the remark this answers is not in the document]
Comment (ghostwords) [reply src/js/background.js]: We should forget the other known DNT domains while we are at it. For example, #1397 is about `medium.com`.

File: src/js/migrations.js (hunk 4 above)
Comment (ghostwords) [reply src/js/migrations.js]: It seems weird how DNT isn't reversible: toggling DNT compliance checking (and unblocking) off, visiting some DNT compliant domains (that seem to perform tracking) and then toggling DNT compliance checking back on does not in fact get you back to where you would have been had you never fiddled with DNT checking.

Comment (ghostwords) [reply src/js/migrations.js]: Let's outline what happens with `eff.org` domains to help understand this situation:
1. Disable DNT checking.
2. Visit `https://stopsesta.org/`, `https://savecrypto.org/`, `https://necessaryandproportionate.org/sign`.
3. `act.eff.org` is seen perform tracking on three sites; it and its parent (`eff.org`) are marked for blocking.
4. Enable DNT checking.
5. Visit the sites again.
6. `anon-stats.eff.org` is still blocked (even though it was never seen tracking), because `eff.org` is still marked for blocking in `action_map`.

When DNT checking is enabled, `act.eff.org` would not (ordinarily) get marked for blocking more than once and so the `eff.org` entry would be there, but set to "allow" instead of "block".

Comment (ghostwords) [reply src/js/migrations.js]: I don't think we need to fix this now, but it seems like a bug. If we handled DNT better, we wouldn't need a migration, for example.

File: src/js/background.js (hunk 5 above)
[the remark this answers is not in the document]
Comment (cowlicks) [reply src/js/background.js]: @ghostwords I'd prefer to do that in a separate PR. Can you make an issue?

File: src/js/migrations.js (hunk 4 above)
Comment (cowlicks) [reply src/js/migrations.js]: Would you mind making an issue for handling DNT better?

**Comment by cowlicks** [comment]
@ghostwords  I looked in to reproducing this yesterday and wasn't able to do so. A user shared their Snitch-map, it included badssl.com, slack-redir.com, and another site I've forgotten.

File: src/js/webrequest.js (hunk 1 above)
Comment (cowlicks) [reply src/js/webrequest.js]: done

File: src/js/background.js (hunk 5 above)
[the remark this answers is not in the document]
Comment (ghostwords) [reply src/js/background.js]: No, I think this change belongs here. This bug isn't exclusive to the EFF. #1397, the issue we claim to be fixing, is about `medium.com`.

[the remark this answers is not in the document]
Comment (ghostwords) [reply src/js/background.js]: Why is the function still called "unblock"?

[the remark this answers is not in the document]
Comment (ghostwords) [reply src/js/background.js]: Should we add a `console.log`, like we do in the other migrations?

**Comment by ghostwords** [comment]
Could you share this debugging info here?

File: src/js/background.js (hunk 5 above)
[the remark this answers is not in the document]
Comment (cowlicks) [reply src/js/background.js]: I'd like to keep this PR small in the interest of getting it merged before the release Monday. However I can add `medium.com` assuming it won't cause further issues.

Because it unblocks the domains, I'll rename it to "forget" or something.

I'll add a console.log.

**Comment by cowlicks** [comment]
@ghostwords that's all I got sorry. @andresbase has access to a spreadsheet where you can get more info.

**Comment by andresbase** [comment]
I have the Etherpad with the report that I sent on the email. Let me know what other info is needed that isn't there and I'll ask the different people that made the reports.

**Comment by ghostwords** [comment]
Do you guys mean the "'is act.eff.org green" EtherCalc?

It would be good to have the people who reported blocking `act.eff.org` double-check that they have DNT checking enabled, and then have them get us debugging info for "eff.org" using instructions on https://gist.github.com/anonymous/8aebb8e48a1ce3c256b21dcfe37af84b.

**Comment by andresbase** [comment]
DNT Enabled:
```
eff.org {
"userAction": "",
"dnt": true,
"heuristicAction": "block",
"nextUpdateTime": 1493548377557
}
www.eff.org {
"userAction": "user_allow",
"dnt": true,
"heuristicAction": "",
"nextUpdateTime": 1502420210596
}
camera1.int.eff.org {
"userAction": "",
"dnt": false,
"heuristicAction": "",
"nextUpdateTime": 1493182477126
}
anon-stats.eff.org {
"userAction": "",
"dnt": false,
"heuristicAction": "block",
"nextUpdateTime": 1493613864400
}
supporters.eff.org {
"userAction": "",
"dnt": true,
"heuristicAction": "allow",
"nextUpdateTime": 1502653704590
}
sentry.eff.org {
"userAction": "",
"dnt": false,
"heuristicAction": "",
"nextUpdateTime": 1493600572223
}
cerb.eff.org {
"userAction": "",
"dnt": false,
"heuristicAction": "block",
"nextUpdateTime": 0
}
**** SNITCH_MAP for eff.org
eff.org [
"browser",
"shipwire.com",
"google.com",
""
]
```

**Comment by andresbase** [comment]
One more with also DNT enabled:
```
**** ACTION_MAP for eff.org
www.eff.org {
  "userAction": "",
  "dnt": true,
  "heuristicAction": "",
  "nextUpdateTime": 1498291452738
}
anon-stats.eff.org {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "allow",
  "nextUpdateTime": 1499817981586
}
eff.org {
  "userAction": "",
  "dnt": true,
  "heuristicAction": "block",
  "nextUpdateTime": 1493248889352
}
w2.eff.org {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1493394897943
}
certbot.eff.org {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1498630654069
}
officewiki.int.eff.org {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1500530607374
}
**** SNITCH_MAP for eff.org
eff.org [
  "google.com",
  "localhost",
  "vanguard.com"
]
```

**Comment by ghostwords** [comment]
The above Badgers learned to block `eff.org` because of `anon-stats.eff.org`/`cerb.eff.org` and `officewiki.int.eff.org`. No mention of `act.eff.org`.

Both sets of snitch map entries are suspicious. There wouldn't be any `eff.org` resources on `vanguard.com`, right? They suggest more Privacy Badger attribution bugs: perhaps Badger misattributes domains loaded on the page you just navigated away from as belonging to the page you are navigating to (in certain circumstances on certain browsers?).

File: src/js/migrations.js (hunk 4 above)
Comment (ghostwords) [reply src/js/migrations.js]: To be clear, the above steps are with this PR's patch applied. Without the patch, `act.eff.org` would not get rechecked for DNT compliance in step 5.

**Comment by ghostwords** [comment]
Are there Chrome users who have reported running into this issue? What do they action/snitch maps for `eff.org` look like?

**Comment by ghostwords** [comment]
One more, this one is Chrome (the others are Firefox):
```
**** ACTION_MAP for eff.org
act.eff.org {
  "dnt": true,
  "heuristicAction": "",
  "nextUpdateTime": 1505654346417,
  "userAction": "user_allow"
}
act.s.eff.org {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1492677557877,
  "userAction": ""
}
action.eff.org {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1494164968971,
  "userAction": ""
}
anon-stats.eff.org {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1505464712499,
  "userAction": ""
}
congressforms.eff.org {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1505569342830,
  "userAction": "user_allow"
}
eff.org {
  "dnt": true,
  "heuristicAction": "block",
  "nextUpdateTime": 1492842782684,
  "userAction": ""
}
sentry.eff.org {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1492862003868,
  "userAction": ""
}
supporters.eff.org {
  "dnt": true,
  "heuristicAction": "block",
  "nextUpdateTime": 1492848888619,
  "userAction": ""
}
www.eff.org {
  "dnt": true,
  "heuristicAction": "",
  "nextUpdateTime": 1503906872351,
  "userAction": ""
}
**** SNITCH_MAP for eff.org
eff.org [
  "standagainstspying.org",
  "necessaryandproportionate.org",
  "fight215.org",
  "reuters.com",
  "missionlocal.org",
  "noglobalwarrants.org",
  "wiredforchange.com"
]
```
`reuters.com` doesn't seem to belong ...

**Comment by ghostwords** [comment]
I can reproduce the attribution bug consistently, in Chrome with caching disabled (might help reproducing). For example, start loading `nytimes.com` and then at some point while the site is still loading, navigate away to `example.com`, a site with no trackers. One interesting thing is that you might see `nyt.com` domains on `example.com` (`nyt.com` is a known first party on `nytimes.com`).

**Comment by ghostwords** [comment]
Merged, thanks! I added a functional test in c5b55718f7b2c1314b26105ac016c27edfe31c1c. I'll work on the attribution bug after today's release.

**Comment by ghostwords** [comment]
This followed up on #1312.
