### PR TITLE
fix for "clicking tabs makes window scroll down"

### LINKED ISSUE #1918: Clicking on the Tracking domains tab makes the screen scroll down
The screen scrolls down when clicking on the Tracking domains tab, this doesn't happen when clicking on any other tab.

### PR DESCRIPTION
**Pull request by aspic2**
Fixes #1918.

src/options.js, line 100. move window back to top of page

### CODE REVIEW

**Comment by ghostwords** [comment]
Hello and welcome!

You can [prepend issue numbers with certain keywords](https://help.github.com/articles/closing-issues-using-keywords/) in the PR's description to automatically resolve those issues when the PR gets merged. This doesn't work when done in the title, however.

**Comment by aspic2** [comment]
Got it, sorry about that!

**Comment by aspic2** [comment]
Thanks for the link! How is this updated solution? 

Is there a way to add both the "#" and id to the URL without explicitly concatenating them?

**Comment by ghostwords** [comment]
Excellent! I'll take a look and hopefully merge tomorrow. Maybe there is a `hash` attribute on the tab object (as in the SO link)?

**Comment by aspic2** [comment]
I'm not seeing a hash attribute in my console, and all the [other solutions](https://stackoverflow.com/a/1511522/) I found look way more convoluted than concatenating, so I'll leave it as-is.

Let me know if I need to make any more changes.

File: src/js/options.js [hunk 1]
```diff
@@ -96,7 +96,7 @@ function loadOptions() {
     activate: function (event, ui) {
       // update options page URL fragment identifier
       // to preserve selected tab on page reload
-      window.location.hash = ui.newPanel.attr('id');
+      history.pushState(null, null, "#" + ui.newPanel.attr('id'));
```
Comment (ghostwords) [inline src/js/options.js]: Sorry, could we make one more change? I think we should use `history.replaceState` instead, since we don't support back button navigation anyway (navigating back in history updates the URL but doesn't change the tab) and it doesn't seem important to support history navigation, easier to just avoid creating new history states.

Comment (aspic2) [reply src/js/options.js]: Sure thing, @ghostwords . Just updated.
