### PR TITLE
Error page keeps the input when reopening on the same page

### LINKED ISSUE #1965: Improve error reporting usability by saving in-progress error reports
From a Privacy Badger support email:

>It is very difficult to use the PB reporting device for broken domains, as several times I started typing on it, then left it to go back to the article and PB so I could report the correct problems, and each time the reporting device had disappeared and the typing I had already entered on it was gone when I brought it back.
It would be much preferable if it would stay there even if one leaves it momentarily instead of having it disappear.

While we can't keep the popup from closing, we could save the state of the popup (probably in the `tabData` object for the associated tab). If a user opens the error reporting interface by clicking "Did Privacy Badger break this site?", types some text without submitting, and closes and reopens the popup, we should show the popup in the state it was left in: with the error report UI active and whatever typed text preserved.

### PR DESCRIPTION
**Pull request by troy-lamerton**
Finishing the work of #2036 by resolving suggestions from the review, and showing the error layout if the user was writing a report for this page.

FIxes #1965

### CODE REVIEW

File: src/js/webrequest.js [hunk 1]
```diff
@@ -775,6 +783,16 @@ function dispatcher(request, sender, sendResponse) {
 
     sendResponse();
 
+  } else if (request.type == "saveErrorText") {
+    let activeTab = badger.tabData[request.tabId];
+    activeTab.errorText = request.errorText;
+
+    sendResponse();
```
Comment (ghostwords) [inline src/js/webrequest.js]: We can remove the `sendResponse` call here since we don't do anything upon response back in the popup.

File: src/js/popup.js [hunk 2]
```diff
@@ -105,7 +105,23 @@ function init() {
     });
   });
 
+  $('#error_input').bind('input propertychange', function() {
```
Comment (ghostwords) [inline src/js/popup.js]: Let's use `.on()` instead of `.bind()`.

File: src/js/popup.js [hunk 3]
```diff
@@ -398,6 +420,11 @@ function refreshPopup() {
     }
   }
 
+  // if there is any saved error text, fill the error input with it
```
Comment (ghostwords) [inline src/js/popup.js]: Should this part be combined with "show error layout if the user was writing an error report" (and live in `init()`)?

Comment (troy-lamerton) [reply src/js/popup.js]: I tried that to start with, but it caused a strange bug as if it created an infinite loop when opening the popup.

File: src/js/popup.js [hunk 4]
```diff
@@ -284,6 +284,7 @@ function send_error(message) {
         $("#report_cancel").prop("disabled", false);
         $("#report_success").toggleClass("hidden", true);
         closeOverlay();
+        delete POPUP_DATA.errorText;
```
Comment (ghostwords) [inline src/js/popup.js]: This doesn't resolve the issue of error text not being cleared after submitting a report successfully and then closing the entire popup before the report UI autocloses. Since the `setTimeout` callback may never happen, we might want to send the "removeErrorText" message earlier, from outside the callback.

**Comment by ghostwords** [comment]
Thank you, merged!

The error text still wasn't getting cleared on quick popup close after a successful report; I fixed that case in ecfa80bccab8445311befdcf8e7b2ebc3d0ca81f.

Here is the combined diff for this PR: https://github.com/EFForg/privacybadger/compare/182c6f8ae7609080bff5f9ab96fcfced339fdbfc~3...182c6f8ae7609080bff5f9ab96fcfced339fdbfc
