### PR TITLE
Fix badge count

### LINKED ISSUE #1608: Badge count not always reflecting the full count of blocked domains in the popup
We seem to have introduced a bug in #1480 where the badge count doesn't reflect the actual number of blocked/cookieblocked trackers in the popup. The bug seems limited to domains that Badger learned to block/cookieblock within the current page load. To reproduce, install Privacy Badger into a new profile, visit three (news) sites at the same time, and compare badge counts to the popup's findings.

### PR DESCRIPTION
**Pull request by ghostwords**
Fixes #1608.

This undoes the `blockedCount` counter optimization from #1480, but preserves the other improvements, plus adds more code cleanup.

`updateBadge` / `getBlockedOriginCount` can still get optimized, but maybe not through caching, at least not simple blocked domain counting. See #1608 for issues with using a simple counter. Let's take a quick look to see if we still need to optimize.

### CODE REVIEW

**Comment by ghostwords** [comment]
Here is a combined diff of the relevant changes from #1408 and this PR, to provide context for what we're changing from production code: https://gist.github.com/anonymous/f6d38a6557df32fdc918b55831af3b06.

**Comment by ghostwords** [comment]
There is some kind of Sinon-Firefox interaction bug that interferes with stubbing certain (WebExtensions?) methods. Stubbing `chrome.browserAction.setBadgeText` works, but stubbing `chrome.browserAction.setBadgeBackgroundColor` (or `chrome.tabs.get`) does not. What happens is that our responder function never gets called and the stub's callCount property never gets incremented. I haven't dug into the root cause, just replaced Sinon's convenience methods with basic workarounds. This certainly confuses my preference for us using an existing popular test helper library instead of rolling our solution.

**Comment by ghostwords** [comment]
I made the badge only get updated for active tabs in 15005f684762e7de5ade320d5c8f6bcf800673e9, avoiding the `getBestAction` reduce over the origin list for backgrounded tabs. The tradeoff is that we now also update the badge upon tab switching.

**Comment by ghostwords** [comment]
There is still an edge case bug, present in production, where if you open several tabs at the same time, and stay on one of them, any just-under-the-threshold domains won't be reflected in the badge count, which is fine, except that these domains might become over the threshold as they get loaded in the other tabs, at which point your active tab's popup results and badge count will disagree. We can attend to it later I think.

**Comment by ghostwords** [comment]
Here is the updated combined diff: https://gist.github.com/ghostwords/f752caa7bb4880191dd343fd58aa703a.

File: src/js/background.js [hunk 1]
```diff
@@ -498,31 +497,64 @@ Badger.prototype = {
...
+        // don't set on background (prerendered) tabs to avoid Chrome errors
+        return;
       }
+
+      if (!tab.active) {
+        // don't set on inactive tabs
+        return;
+      }
+
+      let disabled = tab.url && self.isPrivacyBadgerDisabled(window.extractHostFromURL(tab.url));
```
Comment (cowlicks) [inline src/js/background.js]: I like that this got moved into updateBadge.

File: src/js/background.js [hunk 2]
```diff
@@ -682,20 +714,32 @@ Badger.prototype = {
...
    * @param action the action we are taking
    *
    **/
-  logThirdPartyOriginOnTab: function(tabId, fqdn, action) {
-    if(!this.tabData[tabId].origins.hasOwnProperty(fqdn)) {
-      this.tabData[tabId].origins[fqdn] = action;
-      if (constants.BLOCKED_ACTIONS.has(action)) {
-        this.tabData[tabId].blockedCount += 1;
-        badger.updateBadge(tabId);
+  logThirdPartyOriginOnTab: function (tab_id, fqdn, action) {
```
Comment (cowlicks) [inline src/js/background.js]: Could you add some tests for this? It went from 2 code paths to 4.

File: src/tests/tests/background.js [hunk 3]
```diff
@@ -184,87 +144,102 @@
...
+
     QUnit.module('updateBadge', {
       beforeEach: function() {
-        this.before = beforeMock([
-          'chrome.tabs.get',
-          'chrome.browserAction.setBadgeText',
-          'chrome.browserAction.setBadgeBackgroundColor'
-        ]);
+        // stub chrome.tabs.get manually as we have some sort of issue stubbing with Sinon in Firefox
+        this.chromeTabsGet = chrome.tabs.get;
```
Comment (cowlicks) [inline src/tests/tests/background.js]: I'm fine with removing these here, but do you mind if I include them in future tests? I generally prefer helper methods if they are short and simple, over 3rd party dependencies.  Especially with Sinon,  I can never tell if it is buggy, or if I just don't understand how it works, or if my code is just broken.

File: src/js/background.js [hunk 4]
```diff
@@ -748,6 +788,10 @@ function startBackgroundListeners() {
     });
   });
 
+  chrome.tabs.onActivated.addListener(function (activeInfo) {
```
Comment (cowlicks) [inline src/js/background.js]: Can you put this inside the `startBackgrountdListeners` function?

File: src/tests/tests/background.js (hunk 3 above)
Comment (ghostwords) [reply src/tests/tests/background.js]: My issue with your helpers is that I don't know what they do. Documenting and adding tests would help, but now we're reimplementing parts of Sinon.

It is unfortunate that Sinon and Firefox have some sort of (maybe) WebExtensions-related bug, but I still think it's worth trying to use a more standard solution whenever we can. Sinon's docs are pretty confusing, but there are articles/tutorials/Q&As across the Web. Other open source projects use Sinon so we can look for real-world examples that way. Why get into the business of testing helper libraries?

Also, I tried to keep my workarounds as simple as possible. Do we actually need a helper to do something, or can we wait to add the helper later when we do need it? I would rather keep it simple and wait.

File: src/js/background.js (hunk 4 above)
Comment (ghostwords) [reply src/js/background.js]: This is already inside `startBackgroundListeners` ...

File: src/tests/tests/background.js (hunk 3 above)
Comment (cowlicks) [reply src/tests/tests/background.js]: > Why get into the business of test helper libraries?

This is not my intention. The purpose of most of the code I wrote was to automate mocking and unmocking a list of functions. Not to entirely replace sinon. You could modify it to use sinon if you'd like. Below it looks like you manually reproduce what the test helper was doing. Where you mock, and then manually unmock, `chrome.tabs.get` and `chrome.browserAction.setBadgeBackgroundColor`, you also have to do the same when you mock functions with sinon. I dislike this pattern because we have to manually track mocking and unmocking (whether it is with sinon or a manual mock). The code I wrote makes this pattern nicer.

>  Do we actually need a helper to do something, or can we wait to add the helper later when we do need it?

No we definitely don't need the code I wrote. I don't think we will ever need it because it can be done manually. I just thought it made writing tests easier. It is a matter of preference to me.

Comment (ghostwords) [reply src/tests/tests/background.js]: I think Sinon supports [automatic unmocking](http://sinonjs.org/releases/v2.0.0/sandbox/). It doesn't seem worth getting into yet since keeping track of three stubs is easier and simpler than getting up to speed with this functionality, but it's there.

File: src/js/background.js (hunk 2 above)
Comment (ghostwords) [reply src/js/background.js]: Added: 31f3c741c938139022f76bcec643d9f7ce5891ba.

File: src/tests/tests/background.js (hunk 3 above)
Comment (cowlicks) [reply src/tests/tests/background.js]: Would you like me to add documentation for the code I added? I personally think it is easier and simpler than tracking stubs.

**Comment by cowlicks** [comment]
@ghostwords I think the testing done here is valuable, since it thoroughly flexes the code. However I was thinking the tests should have been more contained to the `logThirdPartyOriginOnTab` function. I'll be more specific next time. 

In general, if I was writing this test for `logThirdPartyTrackerOnTab` I wouldn't assert that `setBadgeText` etc were called, since those are called in `updateBadge`, likewise for `getBlockedOriginCount`. I would just test that `updateBadge` gets called properly, and `tabData` gets updated properly. Since those are the direct effects of this function. And I would instead test `setBadgeText` is called properly inside the test for `updateBadge`, likewise for `getBlockedOriginCount`.

The benefit of testing like this is that it lets you find breakages more precisely. And it limits what tests need to be changed when you refactor or add features.

I usually would prefer to keep tests more isolated, to keep them more maintainable, and useful for finding bugs. For posterity, I wrote up what I was thinking `logThirdPartyOriginOnTab` tests would look like:
```javascript
  QUnit.module(
    "logThirdPartyOriginOnTab",
    {
      beforeEach: function() {
        self = this;
        self.before = badger.updateBadge;
        self.updateBadgeArgs = [];
        badger.updateBadge = function() {
          self.updateBadgeArgs.push(...Array.from(arguments));
        };
        self.fqdn = 'example.com';
        self.tabId = -1;
        badger.tabData[self.tabId] = {
          frames: {},
          origins: {}
        };
      },
      afterEach: function() {
        badger.tabData = {};
        badger.updateBadge = this.before;
      }
    });
  QUnit.test('no fqdn, not blocked', function(assert) {
    badger.logThirdPartyOriginOnTab(this.tabId, this.fqdn, constants.ALLOW);
    assert.ok(badger.tabData[this.tabId].origins[this.fqdn] === false);
    assert.deepEqual(this.updateBadgeArgs, []);
  });
  QUnit.test('no fqdn, blocked', function(assert) {
    badger.logThirdPartyOriginOnTab(this.tabId, this.fqdn, constants.BLOCK);
    assert.ok(badger.tabData[this.tabId].origins[this.fqdn] === true);
    assert.deepEqual(this.updateBadgeArgs, [this.tabId]);
  });
  QUnit.test('yes fqdn, blocked', function(assert) {
    badger.tabData[this.tabId].origins[this.fqdn] = false;
    badger.logThirdPartyOriginOnTab(this.tabId, this.fqdn, constants.BLOCK);
    assert.ok(badger.tabData[this.tabId].origins[this.fqdn] === true);
    assert.deepEqual(this.updateBadgeArgs, [this.tabId]);
  });
```

I think the PR is fine as-is, I just wanted to check in about what I was expecting to see if we are on the same page. I'll merge shortly unless you'd like to make any more changes.
