### PR TITLE
Fix cookie sharing detection in Firefox when first-party isolation is enabled

### LINKED ISSUE #2426: Privacy Badger doesn't learn when privacy.firstparty.isolate is enabled in Firefox
Firefox users can isolate cookies to first parties, by setting `privacy.firstparty.isolate` to `true` in about:config. When this is enabled, Privacy Badger can't identify tracking cookies because it finds that cookies set on one website can't / won't be accessed by other websites.

### PR DESCRIPTION
**Pull request by ghostwords**
Fixes #2426.

Tested learning to block `google-analytics.com` in Chrome, and then both with and without first-party isolation in Firefox 58 and also Firefox 69 (beta). Reviewed background console for any related exceptions.

### CODE REVIEW

File: src/js/background.js [hunk 1]
```diff
@@ -122,6 +123,27 @@ function Badger() {
...
+   * Checks for availability of firstPartyDomain chrome.cookies API parameter.
+   * https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies/getAll#Parameters
+   *
+   * firstPartyDomain is required when privacy.websites.firstPartyIsolate is enabled,
+   * and is in Firefox since Firefox 59. (firstPartyIsolate is in Firefox since 58).
+   *
+   * Not in Chrome.
+   */
+  function testCookiesFirstPartyDomain() {
+    try {
```
Comment (bcyphers) [inline src/js/background.js]: would it be better to use the official APIs here?
for example, you could initially set `firstPartyDomainPotentiallyRequired` to false, then call the async settings fetch like this:
```
function testCookiesFirstPartyDomain() {
  if (browser.privacy.websites.firstPartyIsolate == undefined) {
    return;
  }
  browser.privacy.websites.firstPartyIsolate.get({}).then((got) => {
    self.firstPartyDomainPotentiallyRequired = got;
  });
}
```

File: src/js/background.js [hunk 2]
```diff
@@ -39,6 +39,7 @@ function Badger() {
   var self = this;
 
   self.webRTCAvailable = checkWebRTCBrowserSupport();
+  self.firstPartyDomainPotentiallyRequired = testCookiesFirstPartyDomain();
```
Comment (bcyphers) [inline src/js/background.js]: We should probably call this function periodically in case the user changes the setting during a session.

File: src/js/background.js (hunk 1 above)
Comment (ghostwords) [reply src/js/background.js]: The thing is that `privacy.websites.firstPartyIsolate` is present in Firefox since 58, but `firstPartyDomain` was added in 59. So we have that edge case with Firefox 58. Furthermore, it doesn't matter whether `firstPartyIsolate` is enabled or not; if `firstPartyDomain` is supported, we can set it to `null` when calling `cookies.getAll()` and achieve what we want regardless of `firstPartyIsolate`. So then it seems the easiest and most relevant question is whether `firstPartyDomain` is supported.

File: src/js/background.js (hunk 2 above)
Comment (ghostwords) [reply src/js/background.js]: See my other reply; I think we care about whether `firstPartyDomain` is supported, not whether `firstPartyIsolate` is enabled.

File: src/js/background.js (hunk 1 above)
Comment (ghostwords) [reply src/js/background.js]: A small but still nice thing about not caring about the value of `firstPartyIsolate` is that we avoid an async lookup, which is a source of potential race conditions on initialization. (I'm working on fixing those in the [improve-startup](https://github.com/EFForg/privacybadger/compare/improve-startup?w=1) branch.)

Comment (bcyphers) [reply src/js/background.js]: Makes sense, thanks for the clarification!

File: src/js/background.js (hunk 2 above)
Comment (bcyphers) [reply src/js/background.js]: :+1:

File: src/js/background.js (hunk 1 above)
Comment (bcyphers) [reply src/js/background.js]: Can you add a comment to note that it's okay to use the firstPartyDomain parameter even when firstPartyIsolate is turned *off*? That wasn't clear to me at first, so I thought you'd have to keep checking to see whether the user had updated the setting. Kind of obvious in hindsight but might be helpful to note in the future.
