### PR TITLE
Test char classes pixel tracking

### LINKED ISSUE #2346: Videos broken on dplay.se (fwmrm.net / FreeWheel)
#### What is your browser and browser version?
Firefox ESR 60.6.1

#### What is broken and where?
All gratis videos at  [dplay.se](https://www.dplay.se/)

Example: https://www.dplay.se/videos/sommaren-med-slakten/sommaren-med-slakten-29

Screenshot at 2019-04-06 03:21:37

#### What is the "culprit" domain?
5e529.v.fwmrm.net

#### What is your debug output for this domain?
<details><summary>debug output</summary>

```
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  clobbercookie.js:35
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  clobberlocalstorage.js:35
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  dnt.js:52
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  fingerprinting.js:316
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. clobbercookie.js:35
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  clobberlocalstorage.js:35
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  dnt.js:52
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  fingerprinting.js:316
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  clobberlocalstorage.js:35
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  dnt.js:52
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  fingerprinting.js:316
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  dnt.js:52
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  fingerprinting.js:316
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  clobbercookie.js:35
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  clobberlocalstorage.js:35
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  dnt.js:52
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  fingerprinting.js:316
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  clobbercookie.js:35
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  clobberlocalstorage.js:35
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  dnt.js:52
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  fingerprinting.js:316
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  clobbercookie.js:35
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  clobberlocalstorage.js:35
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  dnt.js:52
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  fingerprinting.js:316
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  clobbercookie.js:35
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  clobberlocalstorage.js:35
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  dnt.js:52
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  fingerprinting.js:316
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  dnt.js:52
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  fingerprinting.js:316
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  clobbercookie.js:35
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  clobberlocalstorage.js:35
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  dnt.js:52
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  fingerprinting.js:316
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. google-search.js:26
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  clobbercookie.js:35
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  clobberlocalstorage.js:35
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  dnt.js:52
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  fingerprinting.js:316
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  dnt.js:52
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  fingerprinting.js:316
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  socialwidgets.js:457
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  clobbercookie.js:35
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  clobberlocalstorage.js:35
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  socialwidgets.js:457
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  supercookie.js:115
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  dnt.js:52
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  socialwidgets.js:457
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  fingerprinting.js:316
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. socialwidgets.js:457
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  supercookie.js:115
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  socialwidgets.js:457
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  supercookie.js:115
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  socialwidgets.js:457
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  clobbercookie.js:35
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  clobberlocalstorage.js:35
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  socialwidgets.js:457
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  supercookie.js:115
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  socialwidgets.js:457
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  supercookie.js:115
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  socialwidgets.js:457
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  dnt.js:52
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  fingerprinting.js:316
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. socialwidgets.js:457
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  dnt.js:52
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  fingerprinting.js:316
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. socialwidgets.js:457
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  supercookie.js:115
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  socialwidgets.js:457
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  supercookie.js:115
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  socialwidgets.js:457
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  supercookie.js:115
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  socialwidgets.js:457
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  dnt.js:52
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  fingerprinting.js:316
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  supercookie.js:115
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  socialwidgets.js:457
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  supercookie.js:115
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  socialwidgets.js:457
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  supercookie.js:115
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  socialwidgets.js:457
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  supercookie.js:115
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  socialwidgets.js:457
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  dnt.js:52
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  fingerprinting.js:316
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  supercookie.js:115
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  socialwidgets.js:457
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  supercookie.js:115
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  socialwidgets.js:457
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  supercookie.js:115
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  socialwidgets.js:457
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  supercookie.js:115
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  socialwidgets.js:457
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  dnt.js:52
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  fingerprinting.js:316
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  supercookie.js:115
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  socialwidgets.js:457
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  supercookie.js:115
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  socialwidgets.js:457
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  supercookie.js:115
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  socialwidgets.js:457
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  supercookie.js:115
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  dnt.js:52
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  fingerprinting.js:316
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. socialwidgets.js:457
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  supercookie.js:115
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. socialwidgets.js:457
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  clobbercookie.js:35
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  supercookie.js:115
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  clobberlocalstorage.js:35
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  dnt.js:52
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  fingerprinting.js:316
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  socialwidgets.js:457
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  supercookie.js:115
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. socialwidgets.js:457
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  supercookie.js:115
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  socialwidgets.js:457
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  supercookie.js:115
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  socialwidgets.js:457
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  dnt.js:52
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  supercookie.js:115
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  fingerprinting.js:316
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  socialwidgets.js:457
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  supercookie.js:115
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  socialwidgets.js:457
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  supercookie.js:115
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  socialwidgets.js:457
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  clobbercookie.js:35
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  supercookie.js:115
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  clobberlocalstorage.js:35
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  dnt.js:52
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  fingerprinting.js:316
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  clobbercookie.js:35
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  clobberlocalstorage.js:35
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  dnt.js:52
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  fingerprinting.js:316
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  clobbercookie.js:35
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  clobberlocalstorage.js:35
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  dnt.js:52
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  fingerprinting.js:316
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  clobbercookie.js:35
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  clobberlocalstorage.js:35
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  dnt.js:52
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  fingerprinting.js:316
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  clobbercookie.js:35
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  clobberlocalstorage.js:35
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  dnt.js:52
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  fingerprinting.js:316
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  dnt.js:52
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  fingerprinting.js:316
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  dnt.js:52
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  fingerprinting.js:316
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  dnt.js:52
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  fingerprinting.js:316
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  dnt.js:52
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  fingerprinting.js:316
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  clobbercookie.js:35
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  clobberlocalstorage.js:35
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  dnt.js:52
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  fingerprinting.js:316
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  dnt.js:52
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  fingerprinting.js:316
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  google-search.js:26
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. socialwidgets.js:457
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  supercookie.js:115
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. socialwidgets.js:457
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  supercookie.js:115
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  socialwidgets.js:457
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  supercookie.js:115
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  socialwidgets.js:457
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  supercookie.js:115
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. socialwidgets.js:457
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  supercookie.js:115
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. socialwidgets.js:457
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  supercookie.js:115
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  socialwidgets.js:457
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  supercookie.js:115
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. socialwidgets.js:457
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. supercookie.js:115
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. socialwidgets.js:457
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  supercookie.js:115
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  socialwidgets.js:457
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. supercookie.js:115
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. socialwidgets.js:457
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  supercookie.js:115
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  socialwidgets.js:457
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  supercookie.js:115
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  socialwidgets.js:457
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  supercookie.js:115
Privacy Badger is ready to rock!  background.js:90:5
Set DEBUG=1 to view console messages.  background.js:91:5
[Exception... "Component returned failure code: 0xc1f30001 (NS_ERROR_NOT_INITIALIZED) [nsIMessageSender.sendAsyncMessage]"  nsresult: "0xc1f30001 (NS_ERROR_NOT_INITIALIZED)"  location: "JS frame :: resource://gre/modules/ExtensionUtils.jsm :: sendAsyncMessage :: line 533"  data: no] (unknown)
[Exception... "Component returned failure code: 0xc1f30001 (NS_ERROR_NOT_INITIALIZED) [nsIMessageSender.sendAsyncMessage]"  nsresult: "0xc1f30001 (NS_ERROR_NOT_INITIALIZED)"  location: "JS frame :: resource://gre/modules/ExtensionUtils.jsm :: sendAsyncMessage :: line 533"  data: no] (unknown)
Promise rejected after context unloaded: sender.tab is undefined
  dnt.js:52
Promise rejected after context unloaded: sender.tab is undefined
  fingerprinting.js:316
TypeError: Argument 1 of PrecompiledScript.executeInGlobal is not an object.[Learn More]  ExtensionContent.jsm:489:18
Error: WebExtension context not found! ExtensionParent.jsm:861:13
[Exception... "Component returned failure code: 0xc1f30001 (NS_ERROR_NOT_INITIALIZED) [nsIMessageSender.sendAsyncMessage]"  nsresult: "0xc1f30001 (NS_ERROR_NOT_INITIALIZED)"  location: "JS frame :: resource://gre/modules/ExtensionUtils.jsm :: sendAsyncMessage :: line 533"  data: no] (unknown)
[Exception... "Component returned failure code: 0xc1f30001 (NS_ERROR_NOT_INITIALIZED) [nsIMessageSender.sendAsyncMessage]"  nsresult: "0xc1f30001 (NS_ERROR_NOT_INITIALIZED)"  location: "JS frame :: resource://gre/modules/ExtensionUtils.jsm :: sendAsyncMessage :: line 533"  data: no] (unknown)
[Exception... "Component returned failure code: 0xc1f30001 (NS_ERROR_NOT_INITIALIZED) [nsIMessageSender.sendAsyncMessage]"  nsresult: "0xc1f30001 (NS_ERROR_NOT_INITIALIZED)"  location: "JS frame :: resource://gre/modules/ExtensionUtils.jsm :: sendAsyncMessage :: line 533"  data: no] (unknown)
Promise rejected after context unloaded: sender.tab is undefined
  dnt.js:52
Promise rejected after context unloaded: sender.tab is undefined
  fingerprinting.js:316
Promise rejected after context unloaded: Message manager disconnected
  socialwidgets.js:457
Error: WebExtension context not found! ExtensionParent.jsm:861:13
[Exception... "Component returned failure code: 0xc1f30001 (NS_ERROR_NOT_INITIALIZED) [nsIMessageSender.sendAsyncMessage]"  nsresult: "0xc1f30001 (NS_ERROR_NOT_INITIALIZED)"  location: "JS frame :: resource://gre/modules/ExtensionUtils.jsm :: sendAsyncMessage :: line 533"  data: no] (unknown)
Promise rejected after context unloaded: sender.tab is undefined
  dnt.js:52
Promise rejected after context unloaded: sender.tab is undefined
  fingerprinting.js:316
Promise rejected after context unloaded: Message manager disconnected
  socialwidgets.js:457
Error: WebExtension context not found! ExtensionParent.jsm:861:13
[Exception... "Component returned failure code: 0xc1f30001 (NS_ERROR_NOT_INITIALIZED) [nsIMessageSender.sendAsyncMessage]"  nsresult: "0xc1f30001 (NS_ERROR_NOT_INITIALIZED)"  location: "JS frame :: resource://gre/modules/ExtensionUtils.jsm :: sendAsyncMessage :: line 533"  data: no]
```
</details>

### LINKED ISSUE #2436: Separator characters aren't ignored when estimating entropy for pixel cookie sharing
~~At first glance, the pixel tracking heuristic and specifically the `estimateMaxEntropy(str)` function can be optimized. The O(n) notation can definitely be improved upon, and at least one of the helper mechanisms in the algorithm doesn't work as expected.~~ While writing tests for it (#2425) I discovered that the portion for ignoring separator characters `._-` doesn't behave as expected, making strings that should estimate to the same entropy value `'google.analytics/123' , 'google.ana.lytics/123'` actually compute to different entropy values.

### PR DESCRIPTION
**Pull request by ablanathtanalba**
Previously known as `rm-sep-chars-pixel-tracking` --- renamed the branch to be more clear about what it is doing: adds some unit tests to cover the different character classes in the pixel tracking heuristic. 

resolves #2436

### CODE REVIEW

**Comment by ablanathtanalba** [comment]
> The tests still pass if I remove the [common character group code](https://github.com/EFForg/privacybadger/blob/5b42504cbc96243664673338a5a6ea0a56d8b943/src/js/utils.js#L157-L166).

I see, I removed the wrong chunk of code before and didn't catch my mistake when looking over the error messaging the test suite returned! Taking another look now.

**Comment by ablanathtanalba** [comment]
It dawned on me that [this section in question](https://github.com/EFForg/privacybadger/blob/5b42504cbc96243664673338a5a6ea0a56d8b943/src/js/utils.js#L157-L166) isn't functioning as expected -- beyond separator characters not being handled properly as first discovered. The initial `for (let chr_class of ... )` loop doesn't iterate over each group, but rather the int index of each group's placement in the array (needs to be a `for...in` loop). Also the string split near the end is just placing the entire string into an array, rather than splitting it an enumerating over each character. Also there should be a `break` statement near the end of the nested loop, if it's discovered that each character belongs to the group. My mistake for not catching it sooner -- I wasn't sure what exactly this block was for. The following commit will be addressing this concern, then a following one for testing it.

**Comment by ghostwords** [comment]
What are the real-world strings that the common character class logic is supposed to help compute entropy for more accurately?

That is, is this a real problem where we are miscategorizing low-entropy strings as high-entropy or vice versa?

**Comment by ablanathtanalba** [comment]
> What are the real-world strings that the common character class logic is supposed to help compute entropy for more accurately?
> 
> That is, is this a real problem where we are miscategorizing low-entropy strings as high-entropy or vice versa?


This block of code seems to help prevent miscategorizing low entropy string values as high ones. 
Here are some example real world tracking strings and their estimated entropy values with & without the code block in question:


TRACKING STRING				| ENTROPY WITH CODE BLOCK 	| ENTROPY WITHOUT CODE BLOCK 	|
________________________________________________________________________________

'W4YARwAAAK13z0nI'			| 96				| 99.66109904793409		|
'82d07aeb-ce29-4e6d-a35f-76ce3545fa38'	| 119.58941141594505		| 210.88731582459258		|
'6472222808240991374'			| 63.11663380285989		| 63.11663380285989		|
'78cf5b85-f0e3-4500-807f-471419b49974'	| 119.58941141594505		| 210.88731582459258		|
'ZQtbgC42A0aDnCOORiLzMjV-iNK'		| 162				| 169.70585990928072		|

**Comment by ablanathtanalba** [comment]
This code block in question definitely seems to lower the entropy value for real world tracking strings, as well as some false positives that showed up in the initial rounds of testing for the pixel tracking heuristic. Here are some results from manual testing I recently did:

- tracking string: `"78cf5b85-f0e3-4500-807f-471419b49974"`
- estimate entropy with code block: `119.58941141594505`
- estimate entropy without code block: `210.88731582459258`

---

- tracking string: `"82d07aeb-ce29-4e6d-a35f-76ce3545fa38"`
- estimate entropy with code block: `119.58941141594505`
- estimate entropy without code block: `210.88731582459258`

---

- false positive tracking string: `"1152x574"`
- estimate entropy with code block: `26.575424759098`
- estimate entropy without code block: `49.3594000115385`

---

- false positive tracking string: `"https%3A%2F%2F"`
- estimate entropy with code block: `84`
- estimate entropy without code block: `88.50699332842306`


So I'm not sure that this code block is increasing the accuracy of the estimation by a lot, but it definitely reduces the false positive likelihood that was a worry when this was first pushed in (and when the code block wasn't working as expected)

**Comment by ablanathtanalba** [comment]
Most recent commit reverts back to the requested changes in the entropy estimation function. The `x` character has been added to the `SEPS` character class, which will exclude strings like `1280x720` from being caught as a false positive. These changes have been run over different sets of scan results, and generally lower the entropy estimation value of the strings, dropping many into the "low entropy" bucket and reducing the number of false positives in general. Strings like `5ce46836` are now classified as low-entropy with these changes.

File: src/js/utils.js [hunk 1]
```diff
@@ -156,12 +156,24 @@ function estimateMaxEntropy(str) {
...
+  for (let chr_class of [BIN, DEC, HEX, ALPHA, ALPHANUM, B64, URL]) {
     let group = chr_class + SEPS;
     // Ignore separator characters when computing entropy. For example, Google
     // Analytics IDs look like "14103492.1964907".
-    if (str.split().every(val => group.includes(val))) {
+
+    // flag to check if each character of input string belongs to the group in question
+    let each_char_in_group = true;
+
+    [...str].forEach(char => {
```
Comment (ghostwords) [inline src/js/utils.js]: The `[...str]` converts the string to an array of chars, but we do this repeatedly, once per character class. Should save to a variable and reuse the variable instead.

File: src/js/utils.js [hunk 2]
```diff
@@ -156,12 +156,24 @@ function estimateMaxEntropy(str) {
...
+      if (!group.includes(char)) {
+        each_char_in_group = false;
```
Comment (ghostwords) [inline src/js/utils.js]: Don't need to keep checking the rest of the group once we find a character that doesn't belong. (`forEach()` doesn't support short-circuiting but we can use a `for...of` instead. Or, we could use a method that short-circuits for us (`every()`), like we originally tried to do.)

File: src/js/utils.js [hunk 3]
```diff
@@ -114,16 +114,16 @@ function explodeSubdomains(fqdn, all) {
...
+  * Note that default quota for local storage is 5MB and
+  * storing fonts, scripts or images in for local storage for
+  * performance is not uncommon. We wouldn't want to estimate entropy
+  * for 5M chars.
+  */
   let MAX_LS_LEN_FOR_ENTROPY_EST = 256;
 
   // common classes of characters that a string might belong to
-  let SEPS = "._-";
+  let SEPS = "._-x";
```
Comment (ghostwords) [inline src/js/utils.js]: Could we add a test for the "x" separator? One of those screen resolution strings from the badger data notebook.

File: src/js/utils.js (hunk 1 above)
Comment (ghostwords) [reply src/js/utils.js]: Ah, I see the reason for using `[...str]`: `.split('')` doesn't handle Unicode properly.

Comment (bcyphers) [reply src/js/utils.js]: Is unicode legal in URLs?

Comment (ghostwords) [reply src/js/utils.js]: I guess URLs are percent-encoded, so in this particular application `.split('')` should be OK.

File: src/js/utils.js (hunk 3 above)
Comment (ablanathtanalba) [reply src/js/utils.js]: Good call -- just added one in

File: src/js/utils.js [hunk 4]
```diff
@@ -114,16 +114,16 @@ function explodeSubdomains(fqdn, all) {
  */
 function estimateMaxEntropy(str) {
   /*
-   * Don't process item + key's longer than LOCALSTORAGE_MAX_LEN_FOR_ENTROPY_EST.
```
Comment (ghostwords) [inline src/js/utils.js]: Nit: please revert the space change to this block.

File: src/js/utils.js [hunk 5]
```diff
@@ -138,10 +138,10 @@ function estimateMaxEntropy(str) {
 
   if (str.length > MAX_LS_LEN_FOR_ENTROPY_EST) {
     /*
-     * Just return a higher-than-threshold entropy estimate.
```
Comment (ghostwords) [inline src/js/utils.js]: Nit: please revert the space change to this block.

File: src/js/utils.js [hunk 6]
```diff
@@ -156,12 +156,27 @@ function estimateMaxEntropy(str) {
...
+  for (let chr_class of [BIN, DEC, HEX, ALPHA, ALPHANUM, B64, URL]) {
     let group = chr_class + SEPS;
     // Ignore separator characters when computing entropy. For example, Google
     // Analytics IDs look like "14103492.1964907".
-    if (str.split().every(val => group.includes(val))) {
+
+    // flag to check if each character of input string belongs to the group in question
+    let each_char_in_group = true;
+
+    let split_str = str.split('');
```
Comment (ghostwords) [inline src/js/utils.js]: This doesn't need to be inside the character group loop, right?

Comment (ghostwords) [reply src/js/utils.js]: Nit: Should be camel case as it is an array, not a string.

File: src/tests/tests/utils.js [hunk 7]
```diff
@@ -515,14 +515,38 @@ QUnit.test("estimateMaxEntropy", assert => {
...
+  assert.equal(
+    utils.estimateMaxEntropy("fizz/buzz+fizzy~buzzy%"),
+    142.82076811925285,
+    "entropy for string from the case-sensitive class of characters is correctly estimated"
+  );
+
+  assert.equal(
+    utils.estimateMaxEntropy("1280x720") < 32,
+    true,
+    "resolution strings with 'x' char from SEPS class are correctly estimated as low entropy"
```
Comment (ghostwords) [inline src/tests/tests/utils.js]: We don't seem to test the "If all characters are upper or lower case, don't consider case when computing entropy." scenario.

Comment (ablanathtanalba) [reply src/tests/tests/utils.js]: Isn't that taken care of in [this](https://github.com/EFForg/privacybadger/blob/88fdf9fd9a6b357fc38450f2e5cd9b1e434c7d48/src/tests/tests/utils.js#L504) ?

Comment (ablanathtanalba) [reply src/tests/tests/utils.js]: Unless you think it's worth having a test that compares a string of mixed cases with one that has the same characters but in all one case?

Comment (ghostwords) [reply src/tests/tests/utils.js]: If I remove the relevant code (below), the tests still pass for some reason.
```javascript
  let sameCase = (str.toLowerCase() == str) || (str.toUpperCase() == str);
  if (sameCase) {
    str = str.toLowerCase();
  }
```

Comment (ablanathtanalba) [reply src/tests/tests/utils.js]: Ah I see, in the test I mentioned, the `. / ` URL characters make the strings fall into the `SEPS` and `B64` character classes. I modified the test so that it depends on the relevant code block to pass.

**Comment by ghostwords** [comment]
Thank you, merged!

Made some tweaks in 94d787e872642a39084056c699b6e799c05fd54b.

File: src/js/utils.js (hunk 1 above)
Comment (ghostwords) [reply src/js/utils.js]: @bcyphers @ablanathtanalba Wait, `estimateMaxEntropy()` is also used with localStorage keys/values, so Unicode does matter. Plus, I just realized, there is no need to split at all, we can just iterate the string itself directly with `for...of`.

This should be fixed in 2213448632d7a6a44c5af0bb5d1fa2c96a91f908
